PROJECT_BASE = "LPDM"

TIME_UNTIL_NEXT_EVENT_TOPIC_GLOBAL = "{base}/time_until_next_event".format(base = PROJECT_BASE)
TIME_UNTIL_NEXT_EVENT_TOPIC_SPECIFIC_AGENT = TIME_UNTIL_NEXT_EVENT_TOPIC_GLOBAL + "/{id}" 

ENERGY_PRICE_TOPIC = "{base}/energy_price".format(base = PROJECT_BASE)
ENERGY_PRICE_TOPIC_SPECIFIC_AGENT = ENERGY_PRICE_TOPIC + "/{id}"

ENERGY_PRICE_FROM_ENERGY_PRODUCER_TOPIC = "{base}/energy_price_from_producer".format(base = PROJECT_BASE)
ENERGY_PRICE_FROM_ENERGY_PRODUCER_TOPIC_SPECIFIC_AGENT = ENERGY_PRICE_FROM_ENERGY_PRODUCER_TOPIC + "/{id}"


POWER_USE_TOPIC = "{base}/power_use".format(base = PROJECT_BASE)
POWER_USE_TOPIC_SPECIFIC_AGENT = POWER_USE_TOPIC + "/{id}"
SET_POWER_TOPIC = "{base}/set_power_use".format(base = PROJECT_BASE)
SET_POWER_TOPIC_SPECIFIC_AGENT = SET_POWER_TOPIC + "/{id}"

CAPACITY_TOPIC = "{base}/capacity".format(base = PROJECT_BASE)
CAPACITY_TOPIC_SPECIFIC_AGENT = POWER_USE_TOPIC + "/{id}"

BASE_SUBSCRIPTION_TOPIC = "{base}/grid_controller/{{id}}".format(base = PROJECT_BASE)
BASE_ADD_CONTROLLED_DEVICE_TOPIC = BASE_SUBSCRIPTION_TOPIC + "/add" 
ADD_POWER_SOURCE_TOPIC = BASE_ADD_CONTROLLED_DEVICE_TOPIC + "/power_source" 
ADD_END_USE_DEVICE_TOPIC = BASE_ADD_CONTROLLED_DEVICE_TOPIC + "/end_use_device"
REMOVE_POWER_SOURCE_TOPIC = ADD_POWER_SOURCE_TOPIC.replace("/add", "/remove") 
REMOVE_END_USE_DEVICE_TOPIC = ADD_END_USE_DEVICE_TOPIC.replace("/add", "/remove")

SYSTEM_TIME_TOPIC = "{base}/system_time".format(base = PROJECT_BASE)
SYSTEM_TIME_TOPIC_SPECIFIC_AGENT = SYSTEM_TIME_TOPIC + "/{id}"

FINISHED_INITIALIZING_TOPIC_BASE = "{base}/init/finished".format(base = PROJECT_BASE)
FINISHED_INITIALIZING_TOPIC = FINISHED_INITIALIZING_TOPIC_BASE+ "/{id}" 

SCENARIO_ID_TOPIC = "{base}/scenario_id".format(base = PROJECT_BASE)

SUBSCRIPTION_TOPIC = "{base}/subscriptions".format(base = PROJECT_BASE)

FINISHED_PROCESSING_MESSSAGE = "{base}/finished_processing".format(base = PROJECT_BASE)
FINISHED_PROCESSING_MESSSAGE_SPECIFIC_AGENT = FINISHED_PROCESSING_MESSSAGE + "/{id}"

FUEL_LEVEL_BASE = "{base}/FUEL_LEVEL".format(base = PROJECT_BASE)
FUEL_LEVEL_TOPIC = FUEL_LEVEL_BASE + "/{id}"

CHANGE_DEVICE_PARAMETER_TOPIC = "{base}/prameter_change".format(base = PROJECT_BASE)
CHANGE_DEVICE_PARAMETER_TOPIC_SPECIFIC_AGENT = CHANGE_DEVICE_PARAMETER_TOPIC + "/{id}"

TERMINATE_TOPIC = "{base}/terminate".format(base = PROJECT_BASE)

ENERGY_PRICE_FROM_INTERNET_TOPIC = "{base}/CBERD_internet_energy_price".format(base = PROJECT_BASE)